{
 "title": "Consul Server Monitoring",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  { "title": "Consul Server Behavior", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "(FIXME) Raft Commit Time",
   "type": "graph",
   "description": "consul_raft_commitTime should remain stable throughout the life of a health Consul cluster. Slowdowns of the commit time typically mean that something is going wrong.",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    { "expr": "consul_raft_commitTime" }
   ]
  },
  {
   "title": "(FIXME) Raft Commits per 5m",
   "type": "graph",
   "description": "FIXME Interrogate the rate interval more\nFIXME Write the description here",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "commits/5m" } },
   "yaxes": [
    { "format": "commits/5m" }
   ],
   "targets": [
    { "expr": "rate(consul_raft_apply[5m])" }
   ]
  },
  {
   "title": "Server Cluster Health - Leadership and Autopilot",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 }
  },
  {
   "title": "(FIXME) Last Contacted Leader",
   "type": "graph",
   "description": "TODO Filter out non-outliers\nTODO Var based on datacenter",
   "gridPos": { "h": 16, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    { "expr": "consul_raft_leader_lastContact" }
   ]
  },
  {
   "title": "(FIXME) Election Events",
   "type": "graph",
   "description": "TODO",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "consul_raft_state_candidate" },
    { "expr": "consul_raft_state_leader" }
   ]
  },
  {
   "title": "(TODO) Autopilot health",
   "type": "graph",
   "description": "TODO",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "consul_autopilot_healthy" }
   ]
  },
  { "title": "Host Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 } },
  {
   "title": "[TODO] Please ensure Consul has CPU, Disk, Memory, and Network bandwidth headroom available! We recommend creating panels here, querying your host stats for each.",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {}
   ]
  },
  { "title": "Feature: DNS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 } },
  {
   "title": "(FIXME) DNS Queries per 5m",
   "type": "graph",
   "gridPos": { "h": 16, "w": 12, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "queries/5m" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(consul_dns_domain_query_count[5m])"
    }
   ]
  },
  {
   "title": "(FIXME) DNS Domain Query Time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "dtdurationms" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "consul_dns_domain_query" }
   ]
  },
  {
   "title": "(FIXME) DNS Reverse Query Time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 47 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "consul_dns_ptr_query" }
   ]
  },
  { "title": "Feature: KV Store", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 55 } },
  {
   "title": "(FIXME) KV Applies per 5m",
   "type": "graph",
   "description": "TODO",
   "gridPos": { "h": 16, "w": 12, "x": 0, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "ops/5m" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(consul_kvs_apply_count[5m])"
    }
   ]
  },
  {
   "title": "(FIXME) KV Apply",
   "type": "graph",
   "description": "TODO",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    { "expr": "consul_kvs_apply" }
   ]
  },
  {
   "title": "(FIXME) Transaction Apply",
   "type": "graph",
   "description": "TODO",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    { "expr": "consul_txn_apply" }
   ]
  },
  {
   "title": "TODO Feature: ACLs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 72 },
   "collapsed": true
  },
  { "title": "TODO Feature: Catalog", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 73 } }
 ]
}